### ISSUE TITLE
How can I remove the extension view id in panel section

### ISSUE THREAD

**Issue by tjx666** [Idered/iridium#11]
Just the word following screenshot which red arrow pointed to.

In fact, I think the activity bar icon would be better to be replaced by npm icon.

![image](https://user-images.githubusercontent.com/41773861/135302069-89914fa3-a2f2-4b8e-a2ed-8e76d6205060.png)

**Comment by Idered** [comment]
Well, you can't. I can remove it in next release. 

Btw, you might have outdated version 🤔  That view should no longer be part of Explorer container. It should have it's own activity icon ![](https://i.imgur.com/VLmcJXY.png )

**Comment by tjx666** [comment]
eeeeee... In fact, it is standalone panel, but I drag it to Explorer panel.
