### ISSUE TITLE
Filter list by dependencies/devDependencies

### ISSUE THREAD

**Issue by jayktaylor** [Idered/iridium#12]
It would be nice to click these buttons at the bottom of the UI to filter the list between `dependencies` and `devDependencies`. Clicking the same button again should unfilter the list.

![Code_xmtYWJ3C6g](https://user-images.githubusercontent.com/7265189/135316069-e46a1507-047e-40e3-a74a-8456d5b7b719.png)

**Comment by Idered** [comment]
Sounds good

**Comment by Idered** [comment]
I've separated dependencies into two lists. I guess that we can close this, @jayktaylor ?
