### ISSUE TITLE
Error searching dependencies

### ISSUE THREAD

**Issue by gabrielfariasnunes** [Idered/iridium#13]
visual studio returns the following message: "The suggestion service is not responding. Please try again later."

**Comment by bielcode** [comment]
> @bielcode ei, estou ciente disso. Estou usando https://npms.io/ que está atualmente indisponível. Estou procurando uma solução alternativa.

https://www.npmjs.com/search/suggestions?q=$QUERY return json :)

**Comment by Idered** [comment]
@bielcode Fixed in 0.4.2 🎉
