### ISSUE TITLE
Update extension title

### ISSUE THREAD

**Issue by misolori** [Idered/iridium#17]
Refs https://github.com/microsoft/vscode/issues/137239

It seems that this extension does not have a proper title attribute, I'd suggest to add this for the extension to appear properly:

![image](https://user-images.githubusercontent.com/10746682/142222051-eaf5805c-7b04-4e9a-bc6f-a632b6a70512.png)

![image](https://user-images.githubusercontent.com/35271042/141817953-538a4845-450e-4cc1-b5cd-44df03d0e5a7.png)

<img width="240" alt="CleanShot 2021-11-15 at 08 37 40@2x" src="https://user-images.githubusercontent.com/35271042/141819513-58d9170a-1235-4199-90c2-69cd671f357e.png">

**Comment by Idered** [comment]
@misolori hey, sorry for delay. I pushed small update which fixes this issue.

I hope that extension still serves you well :)
