### ISSUE TITLE
Node dependencies is not installing packages...?

### ISSUE THREAD

**Issue by Anupheaus** [Idered/iridium#23]
When I click on update to latest version I get a command prompt style window pop open:

![image](https://user-images.githubusercontent.com/2872785/174256119-c6744752-51c8-4d34-8f4e-bd00dc4ba4b0.png)

It eventually does install the package, but does this window need to pop up each time?  Can you not open the prompt as non-interactive or without a GUI please?

**Comment by Idered** [comment]
fixed #32
