### ISSUE TITLE
Sidebar background unnecesary

### ISSUE THREAD

**Issue by biati-digital** [Idered/iridium#24]
Hi, great extension just have a some what annoying issue.

When enabling vibrancy on VS Code (macOS) the extension adds a background in the sidebar, not sure why as the full sidebar already has the same background. Setting the background bg to transparent does not solve this problem. This is the only extension with that problem. Just to give you an example of other extension:

Thunder Client
![CleanShot 2022-09-24 at 03 11 50](https://user-images.githubusercontent.com/1219228/192087934-6a277e42-ab38-423b-813e-180f7ea55762.png)

Node Dependencies
![CleanShot 2022-09-24 at 03 11 59](https://user-images.githubusercontent.com/1219228/192087949-0e694c63-1983-4e18-8047-25d139fdfeb6.png)

I know this is not a bug, but i've more than 80 extensions and this is the only one that applies a background so really hope you can consider removing the sidebar background.

Thank you for a great extension.

**Comment by Idered** [comment]
Fixed by 349c2cf2561c8da495a93c7b0c48e024a3b87792

**Comment by biati-digital** [comment]
It worked, thank you. 👏
