### ISSUE TITLE
NPM Dependencies: Use VS Code terminals instead of CMD popup on Windows

### ISSUE THREAD

**Issue by junalmeida** [Idered/iridium#25]
When an action is taken, such as upgrading a package, a CMD popup appears. It would be nice to see it running on a vscode internal terminal panel.

**Comment by Idered** [comment]
@junalmeida gotcha, I'll take a look this weekend

**Comment by NSG-YEYING** [comment]
请问您解决了吗？如果您解决了，可以告诉我解决方法吗？
Have you solved it? If you solve it, can you tell me the solution?

**Comment by angelhdzmultimedia** [comment]
I just opened a discussion about this! Didn't ocurr to me to check an Issue instead.

**Comment by Idered** [comment]
fixed #34
