### ISSUE TITLE
How to add npm token

### ISSUE THREAD

**Issue by dj-fiorex** [Idered/iridium#27]
I would like to use this marvelous extension but i'm working for a society that has a dedicated npm registry, so i need to export NPM_TOKEN every time i open a new shell to be able to access the packages. How can i configure this plugin to be able to detect packages versions, updates ecc like other packages?
Thanks!

**Comment by Idered** [comment]
Hey @dj-fiorex sorry but this won't work for private packages. I use https://github.com/algolia/npm-search to get autocomplete and check for updates, it supports only public packages
