### ISSUE TITLE
[FEATURE REQUEST] Hidden/Minimized Terminal

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Idered/iridium#34]
Hi. 

I enjoy this extension and promote it, but this empty terminal that pops up is annoying!

So I'm requesting to set it to hidden (preferable) or minimized.

You can also detect the OS, and instead of using CMD in windows, using Powershell which contains options to open windows hidden.

Hope this gets solved soon, I made a new thread in the Discussions few months ago.

Wishing you health, peace, and success. Thank you.

**Comment by Idered** [comment]
Hey @angelhdzmultimedia, I'm looking into this issue right now

**Comment by angelhdzmultimedia** [comment]
> Hey @angelhdzmultimedia, I'm looking into this issue right now

I tried to get "dirty" by sniffing through the source code. Found the NPMClient and saw the usage of spawn. 
So I'm confident the issue is there. By passing to the spawn function some flag.

Oh and I also tried the previous version of the extension to filter out issues with a specific version.

Thank you so much for replying and stepping in to solve it.

**Comment by angelhdzmultimedia** [comment]
Oh man that was blazingly fast! https://github.com/Idered/iridium/commit/c6e64d49661bf521e56041c894bdcac2a4a8382c

🔥🤯🤝🎉

**Comment by Idered** [comment]
@angelhdzmultimedia just released 1.4.0,  enjoy

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia just released 1.4.0, enjoy

> fixed #34

Amazing job! I don't have an income at this time (I am a struggling freelance musician, graphic designer, programmer, gardener/landscaper, and I mostly use this extensions, open source libraries as a way of calming my generalized anxiety, and helping others in groups and in my YouTube channel) , but I have a list of people I will buy a coffee to when my financial issue is solved. You definitely deserve more than a coffee☕🔥! 

It feels so smooth installing Node deps now! 🤯🔥🤝😍

I started following your other works and they look amazing!

With high appreciation, I thank you for your time and kindness, and I wish you health, peace, and success.
