### ISSUE TITLE
Problem with bearded color theme

### ISSUE THREAD

**Issue by smpKlaa** [Idered/iridium#36]
![image](https://github.com/Idered/iridium/assets/96190615/e55e98de-e855-4cb6-9d3c-f81d562326ca)
Search bars dropdown menu is transparent. This happens at least with all bearded color themes. Worked correctly with some other color themes. Problem could be with the color theme but I don't know.

**Comment by Idered** [comment]
@smpKlaa checking

**Comment by Idered** [comment]
https://github.com/Idered/iridium/assets/230404/feaee36e-b2a7-413a-acfe-3727d545b13e

@smpKlaa  works fine. Please check if you don't have any custom css tweaks added

**Comment by smpKlaa** [comment]
How do I do that :D ?

**Comment by Idered** [comment]
okey, I found the issue, it's in monorepo select only, I'll push fix soon

**Comment by Idered** [comment]
pushed version 1.7.4 with a fix - it will be available once it passes store review
