### ISSUE TITLE
"Update all" button?

### ISSUE THREAD

**Issue by vincerubinetti** [Idered/iridium#46]
Thanks for the extension, it's supper useful and I find the DX better than [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) or [npm check updates](https://www.npmjs.com/package/npm-check-updates).

Maybe there could be an "update/upgrade/refresh all" button, for those of use who periodically like to go in and bump everything up to the latest version? Perhaps there could even be different buttons for SemVer, like "Update Minor" and "Update Major".

**Comment by Idered** [comment]
There is update button :

![CleanShot 2024-10-30 at 10 08 03@2x](https://github.com/user-attachments/assets/2a86840d-888f-41f1-8b26-db349a25fb6d)

**Comment by vincerubinetti** [comment]
oh i'm dumb!

**Comment by Idered** [comment]
@vincerubinetti nope, you're not, it's just not the best UI, I'll revamp it in near future
