### ISSUE TITLE
Preserve semver flavour

### ISSUE THREAD

**Issue by schickling** [Idered/iridium#9]
Thanks a lot for this useful extension. Would be great if you could preserve the semver "flavour" (e.g. when `^` is used) like here:

What the extension did:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/1567498/134126301-1229f171-bf1e-40ff-b664-b875ab691b47.png">

What I want:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1567498/134126353-a973d9f5-ac8a-4e46-bf6b-28e84d549739.png">

**Comment by Idered** [comment]
@schickling sounds good, I'll prioritize this as it seems like what most of users would expect

**Comment by Idered** [comment]
@schickling fixed in 0.2.0 🎉
